In [ ]:
# Naman Bothra
# Prn - 25070123078
# EXPERIMENT 12 - Categorical data analysis using python

In [ ]:
import pandas as pd
df = pd.read_csv('/content/Expt11.csv')
print(df)

   Student  Gender  Department Grade
0       S1    Male         CSE     A
1       S2  Female          IT     B
2       S3  Female         CSE     A
3       S4    Male         ECE     C
4       S5    Male          IT     B
5       S6  Female         CSE     A
6       S7    Male  Mechanical     B
7       S8  Female          IT     A
8       S9    Male         CSE     C
9      S10  Female         ECE     B
10     S11    Male         CSE     A
11     S12  Female          IT     B
12     S13    Male  Mechanical     C
13     S14  Female         CSE     A
14     S15    Male          IT     B
15     S16  Female         ECE     A
16     S17    Male         CSE     B
17     S18  Female          IT     C
18     S19    Male  Mechanical     B
19     S20  Female         CSE     A
20     S21    Male         ECE     C
21     S22  Female          IT     B
22     S23    Male         CSE     A
23     S24  Female  Mechanical     B
24     S25    Male          IT     A
25     S26  Female         CSE     C
26     S27    Male         ECE     B
27     S28  Female          IT     A
28     S29    Male  Mechanical     C
29     S30  Female         CSE     B
30     S31    Male          IT     A
31     S32  Female         ECE     B
32     S33    Male         CSE     A
33     S34  Female  Mechanical     C
34     S35    Male          IT     B
35     S36  Female         CSE     A
36     S37    Male         ECE     B
37     S38  Female          IT     C
38     S39    Male  Mechanical     B
39     S40  Female         CSE     A
40     S41    Male          IT     B
41     S42  Female         ECE     A
42     S43    Male         CSE     C
43     S44  Female  Mechanical     B
44     S45    Male          IT     A
45     S46  Female         CSE     B
46     S47    Male         ECE     C
47     S48  Female          IT     A
48     S49    Male  Mechanical     B
49     S50  Female         CSE     A
50     S51    Male          IT     B
51     S52  Female         ECE     C
52     S53    Male         CSE     A
53     S54  Female  Mechanical     B
54     S55    Male          IT     C
55     S56  Female         CSE     A
56     S57    Male         ECE     B
57     S58  Female          IT     A
58     S59    Male  Mechanical     C
59     S60  Female         CSE     B

In [ ]:
display(df['Grade'].value_counts())

Grade
B    24
A    22
C    14
Name: count, dtype: int64

In [ ]:
display(df['Gender'].value_counts())

Gender
Male      30
Female    30
Name: count, dtype: int64

In [ ]:
display(df['Department'].value_counts())

Department
CSE           20
IT            18
ECE           11
Mechanical    11
Name: count, dtype: int64

In [ ]:
# Percentage distributio of grade
print(df['Grade'].value_counts(normalize=True))

Grade
B    0.400000
A    0.366667
C    0.233333
Name: proportion, dtype: float64

In [ ]:
# Gender vs brade analysis
print(pd.crosstab(df['Gender'],df['Grade']))

Grade    A   B  C
Gender
Female  14  11  5
Male     8  13  9

In [ ]:
# Department VS Gender
print(pd.crosstab(df['Department'],df['Gender']))

Gender      Female  Male
Department
CSE             12     8
ECE              5     6
IT               9     9
Mechanical       4     7

In [ ]:
print(pd.crosstab(df['Department'],df['Grade']))

Grade        A  B  C
Department
CSE         13  4  3
ECE          2  5  4
IT           7  8  3
Mechanical   0  7  4

In [ ]:
print(pd.crosstab(df['Department'],df['Grade'],normalize='index')*100)

Grade               A          B          C
Department
CSE         65.000000  20.000000  15.000000
ECE         18.181818  45.454545  36.363636
IT          38.888889  44.444444  16.666667
Mechanical   0.000000  63.636364  36.363636

In [ ]:
# Grouping Data
print(df.groupby('Department')['Grade'].value_counts())

Department  Grade
CSE         A        13
            B         4
            C         3
ECE         B         5
            C         4
            A         2
IT          B         8
            A         7
            C         3
Mechanical  B         7
            C         4
Name: count, dtype: int64

In [ ]:
data = {
'Order_ID':['O1','O2','O3','O4','O5','O6','O7','O8','O9','O10'],

'Category':['Electronics','Clothing','Electronics','Grocery','Clothing',
            'Electronics','Grocery','Clothing','Electronics','Grocery'],

'Payment_Method':['UPI','Card','UPI','Cash','Card',
                  'UPI','Cash','Card','UPI','Cash'],

'Delivery_Type':['Express','Standard','Express','Standard','Express',
                 'Standard','Express','Standard','Express','Standard'],

'Customer_Type':['New','Returning','Returning','New','Returning',
                 'New','Returning','New','Returning','New']
}
print(data)

{'Order_ID': ['O1', 'O2', 'O3', 'O4', 'O5', 'O6', 'O7', 'O8', 'O9', 'O10'], 'Category': ['Electronics', 'Clothing', 'Electronics', 'Grocery', 'Clothing', 'Electronics', 'Grocery', 'Clothing', 'Electronics', 'Grocery'], 'Payment_Method': ['UPI', 'Card', 'UPI', 'Cash', 'Card', 'UPI', 'Cash', 'Card', 'UPI', 'Cash'], 'Delivery_Type': ['Express', 'Standard', 'Express', 'Standard', 'Express', 'Standard', 'Express', 'Standard', 'Express', 'Standard'], 'Customer_Type': ['New', 'Returning', 'Returning', 'New', 'Returning', 'New', 'Returning', 'New', 'Returning', 'New']}

In [ ]:
df_new = pd.DataFrame(data)
display(df_new['Category'].value_counts())

Category
Electronics    4
Clothing       3
Grocery        3
Name: count, dtype: int64

In [ ]:
display(df_new['Payment_Method'].value_counts())

Payment_Method
UPI     4
Card    3
Cash    3
Name: count, dtype: int64

In [ ]:
print(df_new['Category'].value_counts(normalize=True)*100)

Category
Electronics    40.0
Clothing       30.0
Grocery        30.0
Name: proportion, dtype: float64

In [ ]:
# Filtering Data
# Example : Order from electronics category
electronics_orders = df_new[df_new['Category'] == 'Electronics']
print(electronics_orders)

  Order_ID     Category Payment_Method Delivery_Type Customer_Type
0       O1  Electronics            UPI       Express           New
2       O3  Electronics            UPI       Express     Returning
5       O6  Electronics            UPI      Standard           New
8       O9  Electronics            UPI       Express     Returning

In [ ]:
# Sorting Data
sorted_data = df_new.sort_values(by='Category')
print(sorted_data)

  Order_ID     Category Payment_Method Delivery_Type Customer_Type
1       O2     Clothing           Card      Standard     Returning
4       O5     Clothing           Card       Express     Returning
7       O8     Clothing           Card      Standard           New
0       O1  Electronics            UPI       Express           New
2       O3  Electronics            UPI       Express     Returning
5       O6  Electronics            UPI      Standard           New
8       O9  Electronics            UPI       Express     Returning
3       O4      Grocery           Cash      Standard           New
6       O7      Grocery           Cash       Express     Returning
9      O10      Grocery           Cash      Standard           New

In [ ]:
# Display all unique values
print(df_new['Category'].unique())

['Electronics' 'Clothing' 'Grocery']

In [ ]:
# Number of Unique Value
print(df_new['Category'].nunique())

3

In [ ]:
# Crosstabulation - Category vs payment method
print(pd.crosstab(df_new['Category'],df_new['Payment_Method']))

Payment_Method  Card  Cash  UPI
Category
Clothing           3     0    0
Electronics        0     0    4
Grocery            0     3    0

In [ ]:
# Grouping
# Orders by category and payment method
print(df_new.groupby('Category')['Payment_Method'].value_counts())

Category     Payment_Method
Clothing     Card              3
Electronics  UPI               4
Grocery      Cash              3
Name: count, dtype: int64